package IronMan.Dao;

import IronMan.Model.FileCategory;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FileCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filecategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filecategory
     *
     * @mbggenerated
     */
    int insert(FileCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filecategory
     *
     * @mbggenerated
     */
    int insertSelective(FileCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filecategory
     *
     * @mbggenerated
     */
    FileCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filecategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filecategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileCategory record);
    List<FileCategory> selectAll();
    List<FileCategory> selectByCategoryName(String name);
}