package IronMan.Dao;

import IronMan.Model.OperationRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OperationRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int insert(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int insertSelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    OperationRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperationRecord record);
    List<OperationRecord> selectAll();
    List<OperationRecord> selectDownloadByFileIdAndUserId(Integer fileid,Integer userid);
    List<OperationRecord> selectByFileId(Integer fileid);
    List<OperationRecord> selectByUserId(Integer userid);
    List<OperationRecord> selectByOperationType(String operationtype);
}