package IronMan.Dao;

import IronMan.Model.ScoreRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ScoreRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scorerecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scorerecord
     *
     * @mbggenerated
     */
    int insert(ScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scorerecord
     *
     * @mbggenerated
     */
    int insertSelective(ScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scorerecord
     *
     * @mbggenerated
     */
    ScoreRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scorerecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scorerecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScoreRecord record);
    List<ScoreRecord> selectAll();
    List<ScoreRecord> selectCommentByFileId(Integer fileid);
    List<ScoreRecord> selectCommentByUserId(Integer userid);
    List<ScoreRecord> selectCommentByFileIdAndUserId(Integer fileid,Integer userid);
}