package IronMan.Service;

import IronMan.Model.OperationRecord;

import java.util.List;

public interface OperationRecordService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int insert(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int insertSelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    OperationRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperationRecord record);
    List<OperationRecord> selectAll();
    List<OperationRecord> selectDownloadByFileIdAndUserId(Integer fileid,Integer userid);
    List<OperationRecord> selectByFileId(Integer fileid);
    List<OperationRecord> selectByUserId(Integer userid);
    List<OperationRecord> selectByOperationType(String operationtype);
    List<OperationRecord> searchOperation(String userid,String fileid,String operationtype);
}