package IronMan.Model;

import java.io.Serializable;

public class OperationRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecord.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecord.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecord.fileid
     *
     * @mbggenerated
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecord.operationtype
     *
     * @mbggenerated
     */
    private String operationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationrecord.datail
     *
     * @mbggenerated
     */
    private String datail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecord.id
     *
     * @return the value of operationrecord.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecord.id
     *
     * @param id the value for operationrecord.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecord.userid
     *
     * @return the value of operationrecord.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecord.userid
     *
     * @param userid the value for operationrecord.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecord.fileid
     *
     * @return the value of operationrecord.fileid
     *
     * @mbggenerated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecord.fileid
     *
     * @param fileid the value for operationrecord.fileid
     *
     * @mbggenerated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecord.operationtype
     *
     * @return the value of operationrecord.operationtype
     *
     * @mbggenerated
     */
    public String getOperationtype() {
        return operationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecord.operationtype
     *
     * @param operationtype the value for operationrecord.operationtype
     *
     * @mbggenerated
     */
    public void setOperationtype(String operationtype) {
        this.operationtype = operationtype == null ? null : operationtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operationrecord.datail
     *
     * @return the value of operationrecord.datail
     *
     * @mbggenerated
     */
    public String getDatail() {
        return datail;
    }

    public OperationRecord(Integer id, Integer userid, Integer fileid, String operationtype, String datail) {
        this.id = id;
        this.userid = userid;
        this.fileid = fileid;
        this.operationtype = operationtype;
        this.datail = datail;
    }

    public OperationRecord(Integer userid, Integer fileid, String operationtype, String datail) {
        this.userid = userid;
        this.fileid = fileid;
        this.operationtype = operationtype;
        this.datail = datail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operationrecord.datail
     *
     * @param datail the value for operationrecord.datail
     *
     * @mbggenerated
     */
    public void setDatail(String datail) {
        this.datail = datail == null ? null : datail.trim();
    }
}