package IronMan.Model;

import java.io.Serializable;

public class Resource implements Serializable {
    public Resource(Integer userid, String filename, String filetype, Integer category, String filelocation, Double filescore, String uploaddate, String changedate, String filestate, String fileintroduce) {
        this.userid = userid;
        this.filename = filename;
        this.filetype = filetype;
        this.category = category;
        this.filelocation = filelocation;
        this.filescore = filescore;
        this.uploaddate = uploaddate;
        this.changedate = changedate;
        this.filestate = filestate;
        this.fileintroduce = fileintroduce;
    }

    public Resource(Integer id, Integer userid, String filename, String filetype, Integer category, String filelocation, Double filescore, String uploaddate, String changedate, String filestate, String fileintroduce) {
        this.id = id;
        this.userid = userid;
        this.filename = filename;
        this.filetype = filetype;
        this.category = category;
        this.filelocation = filelocation;
        this.filescore = filescore;
        this.uploaddate = uploaddate;
        this.changedate = changedate;
        this.filestate = filestate;
        this.fileintroduce = fileintroduce;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filename
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filetype
     *
     * @mbggenerated
     */
    private String filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filelocation
     *
     * @mbggenerated
     */
    private String filelocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filescore
     *
     * @mbggenerated
     */
    private Double filescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.uploaddate
     *
     * @mbggenerated
     */
    private String uploaddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.changedate
     *
     * @mbggenerated
     */
    private String changedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filestate
     *
     * @mbggenerated
     */
    private String filestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.fileintroduce
     *
     * @mbggenerated
     */
    private String fileintroduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.userid
     *
     * @return the value of resource.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.userid
     *
     * @param userid the value for resource.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filename
     *
     * @return the value of resource.filename
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filename
     *
     * @param filename the value for resource.filename
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filetype
     *
     * @return the value of resource.filetype
     *
     * @mbggenerated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filetype
     *
     * @param filetype the value for resource.filetype
     *
     * @mbggenerated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.category
     *
     * @return the value of resource.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.category
     *
     * @param category the value for resource.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filelocation
     *
     * @return the value of resource.filelocation
     *
     * @mbggenerated
     */
    public String getFilelocation() {
        return filelocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filelocation
     *
     * @param filelocation the value for resource.filelocation
     *
     * @mbggenerated
     */
    public void setFilelocation(String filelocation) {
        this.filelocation = filelocation == null ? null : filelocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filescore
     *
     * @return the value of resource.filescore
     *
     * @mbggenerated
     */
    public Double getFilescore() {
        return filescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filescore
     *
     * @param filescore the value for resource.filescore
     *
     * @mbggenerated
     */
    public void setFilescore(Double filescore) {
        this.filescore = filescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.uploaddate
     *
     * @return the value of resource.uploaddate
     *
     * @mbggenerated
     */
    public String getUploaddate() {
        return uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.uploaddate
     *
     * @param uploaddate the value for resource.uploaddate
     *
     * @mbggenerated
     */
    public void setUploaddate(String uploaddate) {
        this.uploaddate = uploaddate == null ? null : uploaddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.changedate
     *
     * @return the value of resource.changedate
     *
     * @mbggenerated
     */
    public String getChangedate() {
        return changedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.changedate
     *
     * @param changedate the value for resource.changedate
     *
     * @mbggenerated
     */
    public void setChangedate(String changedate) {
        this.changedate = changedate == null ? null : changedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filestate
     *
     * @return the value of resource.filestate
     *
     * @mbggenerated
     */
    public String getFilestate() {
        return filestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filestate
     *
     * @param filestate the value for resource.filestate
     *
     * @mbggenerated
     */
    public void setFilestate(String filestate) {
        this.filestate = filestate == null ? null : filestate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.fileintroduce
     *
     * @return the value of resource.fileintroduce
     *
     * @mbggenerated
     */
    public String getFileintroduce() {
        return fileintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.fileintroduce
     *
     * @param fileintroduce the value for resource.fileintroduce
     *
     * @mbggenerated
     */
    public void setFileintroduce(String fileintroduce) {
        this.fileintroduce = fileintroduce == null ? null : fileintroduce.trim();
    }
}