package IronMan.Model;

import java.io.Serializable;

public class ScoreRecord implements Serializable {
    public ScoreRecord(Integer id, Integer userid, Integer fileid, Double score, String date) {
        this.id = id;
        this.userid = userid;
        this.fileid = fileid;
        this.score = score;
        this.date = date;
    }

    public ScoreRecord(Integer userid, Integer fileid, Double score, String date) {
        this.userid = userid;
        this.fileid = fileid;
        this.score = score;
        this.date = date;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scorerecord.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scorerecord.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scorerecord.fileid
     *
     * @mbggenerated
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scorerecord.score
     *
     * @mbggenerated
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scorerecord.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scorerecord.id
     *
     * @return the value of scorerecord.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scorerecord.id
     *
     * @param id the value for scorerecord.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scorerecord.userid
     *
     * @return the value of scorerecord.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scorerecord.userid
     *
     * @param userid the value for scorerecord.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scorerecord.fileid
     *
     * @return the value of scorerecord.fileid
     *
     * @mbggenerated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scorerecord.fileid
     *
     * @param fileid the value for scorerecord.fileid
     *
     * @mbggenerated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scorerecord.score
     *
     * @return the value of scorerecord.score
     *
     * @mbggenerated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scorerecord.score
     *
     * @param score the value for scorerecord.score
     *
     * @mbggenerated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scorerecord.date
     *
     * @return the value of scorerecord.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scorerecord.date
     *
     * @param date the value for scorerecord.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}